# Generated by Django 5.1.4 on 2024-12-30 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(editable=False, max_length=255)),
                ('payer_email', models.EmailField(editable=False, max_length=254)),
                ('amount', models.IntegerField(editable=False)),
                ('cardholder_name', models.CharField(editable=False, max_length=255)),
                ('payment_intent_id', models.CharField(editable=False, max_length=255)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('attendance', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='app.attendance')),
            ],
        ),
    ]
